'use client'
import DataCard from "@/components/data-cards/cards"
import "../styles/style.css"
import React, { useState, useEffect } from 'react'
import LineGraph from "@/components/visualizations/line";
import BarGraph from "@/components/visualizations/bar";


export default function Financials(){
    const data = [
        {
          name: 'Page D',
          uv: 2780,
          pv: 3908,
          cv: 4908,
          dv: 1908,
          amt: 2000,
        },
        {
          name: 'Page E',
          uv: 1890,
          pv: 4800,
          cv: 2133,
          dv: 611,
          amt: 2181,
        },
        {
          name: 'Page F',
          uv: 2390,
          pv: 3800,
          cv: 6774,
          dv: 1233,
          amt: 2500,
        },
        {
          name: 'Page G',
          uv: 3490,
          pv: 4300,
          cv: 722,
          dv: 1111,
          amt: 2100,
        },
    ];
    const mrr = [
        {
          name: 'January',
          uv: 4000,
          pv: 2400,
          amt: 2400,
        },
        {
          name: 'February',
          uv: 3000,
          pv: 1398,
          amt: 2210,
        },
        {
          name: 'March',
          uv: 2000,
          pv: 9800,
          amt: 2290,
        },
        {
          name: 'April',
          uv: 2780,
          pv: 3908,
          amt: 2000,
        },
        {
          name: 'May',
          uv: 1890,
          pv: 4800,
          amt: 2181,
        },
        {
          name: 'June',
          uv: 2390,
          pv: 3800,
          amt: 2500,
        },
        {
          name: 'July',
          uv: 3490,
          pv: 4300,
          amt: 2100,
        },
        {
            name: 'August',
            uv: 2410,
            pv: 5215,
            amt: 2100,
        },
        {
            name: 'September',
            uv: 8239,
            pv: 2000,
            amt: 2100,
        },
        {
            name: 'October',
            uv: 1000,
            pv: 2000,
            amt: 2100,
        },
        {
            name: 'November',
            uv: 6000,
            pv: 7120,
            amt: 2100,
        },
        {
            name: 'December',
            uv: 4500,
            pv: 3100,
            amt: 2100,
        },
    ];
    return(
        <div className='container'>
            <div className="top-container">
                <h1>Robodine</h1>
                <div style={{ width:'100%', display: "flex", flexDirection:"row", justifyContent:'space-between' }}>
                    <div style={{ width:'60vw', display: "flex", flexDirection:"column" , alignItems:'flex-start'}}>
                        <div style={{ width:'100%', display: "flex", flexDirection:"row", justifyContent:'space-between' }}>
                            <DataCard title={'Monthly Recurring Revenue'} x={'uv'} width={150} height={100} type='bar' data={data}></DataCard>
                            <DataCard title={'Average Contract Value'} x={'uv'} width={150} height={100} type='bar' data={data}></DataCard>
                            <DataCard title={'Monthly Gross Value'} x={'uv'} width={150} height={100} type='bar' data={data}></DataCard>
                            <DataCard title={'Monthly Net Value'} x={'uv'} width={150} height={100} type='bar' data={data}></DataCard>
                        </div>
                        <div className="mrr-growth-container">
                            <h2>ACCOUNT & MONTHLY RECURRING REVENUE GROWTH</h2>

                            <div className="description-container">
                                <div className="mrr-description">
                                    <h2>Ksh. 363,805</h2>
                                    <h1>MRR</h1>
                                    <p>Measure of how fast your monthly recurring revenue is growing.</p>
                                </div>
                                <div className="mrr-description">
                                    <h2>Ksh. 3,200</h2>
                                    <h1>Avg. MRR/Customer</h1>
                                    <p>Measure of the revenue generated by each user over a given period of time, taken as an average.</p>
                                </div>
                            </div>
                            <LineGraph
                            keys = {['uv','pv']}
                            data = {mrr}
                            width = {800}
                            xaxis = {'name'}
                            yaxis = {'uv'}
                            height = {400}></LineGraph>

                        </div>
                            
                    </div>

                    <div style={{ width:'30vw', display: 'flex', flexDirection:'column', alignItems:'flex-end'}}>
                    <div className="financial-monitoring-container">
                    <h2>FINANCIAL MONITORING</h2>
                    <p>July 16,2023 - October 16,2023</p>
                    <div class="grid-container">
                        <div class="grid-item">
                        <h1>387,098</h1>
                        <h2>ACCOUNTS RECEIVABLE</h2>
                        </div>
                        <div class="grid-item">
                        <h1>387,098</h1>
                        <h2>ACCOUNTS PAYABLE</h2>
                        </div>
                        <div class="grid-item">
                        <h1>387,098</h1>
                        <h2>MONTHLY BURN</h2>
                        </div>
                        <div class="grid-item">
                        <h1>387,098</h1>
                        <h2>NET MONTHLY BURN</h2>
                        </div>
                    </div>
    
                    <div class="financial-monitoring-graphs">
                        <div className="label-container">
                            <h1>JUL</h1>
                        </div>
                        
                        
                        <div className="bar-graph-container">
                        <BarGraph
                            color={"#000"}
                            data = {data}
                            width = {90}
                            height = {70}
                            x = {'uv'}></BarGraph>
                        </div>
                    </div>
                    <div class="financial-monitoring-graphs">
                        <div className="label-container">
                            <h1>AUG</h1>
                        </div>
                        <div className="bar-graph-container">
                        <BarGraph
                            color={"#000"}
                            data = {data}
                            width = {90}
                            height = {70}
                            x = {'pv'}></BarGraph>
                        </div>
                    </div>
                    <div class="financial-monitoring-graphs">
                        <div className="label-container">
                            <h1>SEP</h1>
                        </div>
                        <div className="bar-graph-container">
                            <BarGraph
                            color={"#000"}
                            data = {data}
                            width = {90}
                            height = {70}
                            x = {'cv'}></BarGraph>
                        </div>
                    </div>
                    <div class="financial-monitoring-graphs">
                        <div className="label-container">
                            <h1>OCT</h1>
                        </div>
                        <div className="bar-graph-container">
                            <BarGraph
                            color={"#000"}
                            data = {data}
                            width = {90}
                            height = {70}
                            x = {'dv'}></BarGraph>
                        </div>
                    </div>
                </div>                        

                    </div>
                </div>
                
            </div>
        </div>
    )
}